version: '3.8'
services:

  node:
    container_name: csv-column-mapper-node
    build:
      context: ./
      dockerfile: node/Dockerfile
    tty: true
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app